//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBnB_Clone_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int ID_Cate { get; set; }
        public Nullable<int> ID_Rooms { get; set; }
        public string Name_Cate { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
